language: node_js
node_js: 
  - 8.11.2

script:
  - npm install
  - npm run build

branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build
