language: node_js
node_js: 
  - 8.16.2

script:
  - yarn
  - yarn test
  - yarn build

branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
  - wget https://gist.githubusercontent.com/dayvidwhy/6c61cc49ee5bb8fe706b8e42aba45608/raw/3eeb166a5be7eb5767d1ef3a93260b0344bcf8aa/discord.sh
  - chmod +x discord.sh
  - ./discord.sh success $WEBHOOK_URL
after_failure:
  - wget https://gist.githubusercontent.com/dayvidwhy/6c61cc49ee5bb8fe706b8e42aba45608/raw/3eeb166a5be7eb5767d1ef3a93260b0344bcf8aa/discord.sh
  - chmod +x discord.sh
  - ./discord.sh failure $WEBHOOK_URL